import os
import google.generativeai as genai

# --- Configuration ---
GEMINI_API_KEY = os.getenv("GOOGLE_API_KEY")

# Configure the Gemini API client
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

def generate_escalation_dialogue(level):
    """
    Generates a spoken warning for an intruder based on the escalation level.
    
    Args:
        level (int): The current escalation level (1, 2, or 3).

    Returns:
        str: A creative, spoken warning generated by the LLM.
    """
    if not GEMINI_API_KEY:
        # Fallback dialogue if API key is missing
        fallback_dialogue = {
            1: "Excuse me, I don't recognize you. You are in a restricted area.",
            2: "You are not authorized to be here. Please leave the area immediately.",
            3: "Final warning. Authorities will be notified. Leave now."
        }
        return fallback_dialogue.get(level, "Security Alert.")

    try:
        model = genai.GenerativeModel('gemini-1.5-flash')

        # Craft a creative prompt for the LLM
        system_prompt = "You are a firm but polite home security AI. Your voice is calm but authoritative. Your goal is to make an unauthorized person leave."
        
        user_prompts = {
            1: "Generate a short, verbal, first-level warning for an unrecognized person. Be polite but clear they are in a restricted area.",
            2: "Generate a short, verbal, second-level warning. The tone is now more serious. Command them to leave immediately.",
            3: "Generate a short, verbal, final warning. The tone is severe. State that this is the last chance before authorities are alerted."
        }
        
        prompt = user_prompts.get(level, "Generate a generic security alert.")
        
        full_prompt = f"{system_prompt}\n\nTask: {prompt}"

        response = model.generate_content(full_prompt)
        
        # Clean up the response to be a single, speakable line
        text = response.text.replace("*", "").replace("\n", " ").strip()
        return text

    except Exception as e:
        print(f"❌ Could not generate dialogue from LLM: {e}")
        # Return fallback on API error
        return generate_escalation_dialogue(0) # Will trigger the fallback
generate_escalation_dialogue(3)